In [2]:
import pandas as pd

# Instructions

1. Head back to the [data sets page](https://github.com/michaelschung/bc-data-processing/tree/master/datasets), and pick one data set that you find particularly interesting.
2. Download the file and use Pandas to load that data set. Before moving on, make sure that it downloaded as a `.csv` file! Check the assignment posting on Classroom if you're having issues.
3. Explore the data by querying the DataFrame. Use this document to record your explorations according to the specifications below.

_Note: There are tons of free data sets out there for you to explore, and in the future you'll be able to use any that you like. For this assignment, however, pick one of the data sets that I've provided for you._

---

### Recording Explorations

Make at least three _thoughtful queries_ into the DataFrame. A thoughtful query consists of:

- A concrete question (in English) that you're trying to answer
- The query itself (in Python, using Pandas)
- 2-3 sentences (in English) that use the query results to answer the initial question

_Note: these instructions are intentionally vague. It's up to you to take this as seriously as you want, but I strongly encourage you to dig deep and learn something from the data you choose to look at. If you think you've asked all possible interesting questions, ask one more._

# Your "Thoughtful Queries"

In [3]:
# Load your CSV file here, and preview the first 10-15 rows
pokemonMatchup = pd.read_csv("pokemon_type_matchup.csv", index_col = 0)
pokemonMatchup

,Number,Normal,Fire,Water,Electric,Grass,Ice,Fighting,Poison,Ground,Flying,Psychic,Bug,Rock,Ghost,Dragon,Dark,Steel,Fairy
Name,,,,,,,,,,,,,,,,,,,
Bulbasaur,#001,*1,*2,*0.5,*0.5,*0.25,*2,*0.5,*1,*1,*2,*2,*1,*1,*1,*1,*1,*1,*0.5
Ivysaur,#002,*1,*2,*0.5,*0.5,*0.25,*2,*0.5,*1,*1,*2,*2,*1,*1,*1,*1,*1,*1,*0.5
Venusaur,#003,*1,*2,*0.5,*0.5,*0.25,*2,*0.5,*1,*1,*2,*2,*1,*1,*1,*1,*1,*1,*0.5
Charmander,#004,*1,*0.5,*2,*1,*0.5,*0.5,*1,*1,*2,*1,*1,*0.5,*2,*1,*1,*1,*0.5,*0.5
Charmeleon,#005,*1,*0.5,*2,*1,*0.5,*0.5,*1,*1,*2,*1,*1,*0.5,*2,*1,*1,*1,*0.5,*0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Eternatus,#890,*1,*0.5,*0.5,*0.5,*0.25,*2,*0.5,*0.5,*2,*1,*2,*0.5,*1,*1,*2,*1,*1,*1
Kubfu,#891,*1,*1,*1,*1,*1,*1,*1,*1,*1,*2,*2,*0.5,*0.5,*1,*1,*0.5,*1,*2
Urshifu,#892,*1,*1,*1,*1,*1,*1,*2,*1,*1,*2,*0,*1,*0.5,*0.5,*1,*0.25,*1,*4
Urshifu Rapid Strike,#892,*1,*0.5,*0.5,*2,*2,*0.5,*1,*1,*1,*2,*2,*0.5,*0.5,*1,*1,*0.5,*0.5,*2
Zarude,#893,*1,*2,*0.5,*0.5,*0.5,*2,*2,*2,*0.5,*2,*0,*4,*1,*0.5,*1,*0.5,*1,*2

## Thoughtful Query #1

Question: _(edit this cell to record your question)_

In [8]:
# Query 1 here
#Which pokemon have the best(and worst) defensive type in the game? (least weaknesses and most resistances/immunities && most weaknesses and least resistances/immunities)
pokemon = pokemonMatchup.drop("Number", axis = 1)

cols = ['Normal', 'Fire', 'Water', 'Electric', 'Grass', 'Ice', 'Fighting', 'Poison', 'Ground', 'Flying', 'Psychic', 'Bug', 'Rock', 'Ghost', 'Dragon', 'Dark', 'Steel', 'Fairy']#Can't select columns by index
for col in cols:
    pokemon[col] = pokemon[col].str.slice_replace(0,1, '')
    pokemon[col] = pokemon[col].astype(float)

defenseScore = pokemon.sum(axis=1)
pokemon['Defense'] = defenseScore

bestDefensivePokemondf = pokemon[pokemon["Defense"]==defenseScore.min()]
bestDefensivePokemon = bestDefensivePokemondf.index

worstDefensivePokemondf = pokemon[pokemon["Defense"]==defenseScore.max()]
worstDefensivePokemon = worstDefensivePokemondf.index

print('The best defensive pokemon are', end=" ")
for poke in bestDefensivePokemon:
    print(poke, end=", ")
print('and the weakest defensive pokemon are', end=" ")
for poke in worstDefensivePokemon:
    print(poke, end=", ")

#This code calculates a defense score for each pokemon(the lower the score the more resistances/immunities they have, adds that as a column to the original df and then uses that final common to search for pokemon with the highest and lowest defense values)
#The actual query finds the pokemon with highest and lowest defense scores

The best defensive pokemon are Mawile, Klefki, Magearna, Zacian Crown Sword, and the weakest defensive pokemon are Snover, Abomasnow,

Insight: _(edit this cell to record your insight)_

## Thoughtful Query #2

Question: _(edit this cell to record your question)_

In [10]:
# Query 2 here
#What is the best(and worst) offensive type? (If a random pokemon is choosen, what type move is most likely to do the most damage?)
pokemon = pokemonMatchup.drop("Number", axis = 1)

cols = ['Normal', 'Fire', 'Water', 'Electric', 'Grass', 'Ice', 'Fighting', 'Poison', 'Ground', 'Flying', 'Psychic', 'Bug', 'Rock', 'Ghost', 'Dragon', 'Dark', 'Steel', 'Fairy']#Can't select columns by index
for col in cols:
    pokemon[col] = pokemon[col].str.slice_replace(0,1, '')
    pokemon[col] = pokemon[col].astype(float)

offensiveType = pokemon.sum()
bestOffensiveType = offensiveType.idxmax()
worstOffensiveType = offensiveType.idxmin()

print('The best offensive type is', bestOffensiveType, 'and the worst offensive type is', worstOffensiveType)

#This code calculates the total offensive power of every type based on the pokemon in the game right now and finds the types with highest and lowest offensive power
#The actual query is finding the types with highest and lowest values

The best offensive type is Rock and the worst offensive type is Normal

Insight: _(edit this cell to record your insight)_

## Thoughtful Query #3

Question: _(edit this cell to record your question)_

In [11]:
# Query 3 here
#What is the most common resistance and what percent of pokemon resist that type? (If a random pokemon is choosen, which type is it most likely to resist?)
pokemon = pokemonMatchup.drop("Number", axis = 1)

cols = ['Normal', 'Fire', 'Water', 'Electric', 'Grass', 'Ice', 'Fighting', 'Poison', 'Ground', 'Flying', 'Psychic', 'Bug', 'Rock', 'Ghost', 'Dragon', 'Dark', 'Steel', 'Fairy']#Can't select columns by index
for col in cols:
    pokemon[col] = pokemon[col].str.slice_replace(0,1, '')
    pokemon[col] = pokemon[col].astype(float)

commonResistance = 0
for col in cols:
    resistances = len(pokemon[pokemon[col]<1])
    if resistances > commonResistance:
        commonResistance = resistances
        commonResistanceType = pokemon[col]

percentResist = round(commonResistance/len(commonResistanceType)*100, 2)
print(percentResist, '% of pokemon resist', commonResistanceType.name)

#This code calculates the most common resistance based on current pokemon and then the % of pokemon that have that restance
#The actual query finds the type with the current highest # of pokemon that resist it

39.58 % of pokemon resist Grass

Insight: _(edit this cell to record your insight)_